# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json
import os
from instructionsWindow import Ui_MainWindow
import json_struct
from pypancake import pyPancakeSwap




class Ui_Dialog(object):
    
    def __init__(self):
        try:
            f = open(os.path.join(os.path.dirname(__file__),"data.json"))
            self.data = json.load(f)
        except:
            f = open(os.path.join(os.path.dirname(__file__),"data.json"))
            self.data = json.load(json_struct.json_s)
            json.dump(self.data,f)
            f.close()

        self.pancake = pyPancakeSwap()

    def instWindow(self):
        self.intwin = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.intwin)
        self.intwin.show()

    def closefn(self):
        exit(0)

    def returnText(self,obj):
        return obj.toPlainText()

    def reset(self):
        f = open(os.path.join(os.path.dirname(__file__),"data.json"),'w')
        json.dump(json_struct.json_s,f)
        f.close()
        self.data = json_struct.json_s
        self.feedData()

    def start_bot_fn(self):
        self.save()

    def save(self):
        self.data['wallet_address'] = self.returnText(self.wallAdd)
        self.data['private_key'] = self.returnText(self.pvtKey)
        self.data['telegram_api_key'] = self.returnText(self.tele_api)
        self.data['telegram_hash'] = self.returnText(self.tele_hash)

        self.data['amount_BNB'] = self.returnText(self.amt)
        self.data['gas'] = self.returnText(self.gas)
        self.data['gasPrice'] = self.returnText(self.gasPrice)
        self.data['transaction_hash'] = self.returnText(self.pay_txn_hash)

        self.data['channel_1']['selected'] = self.c1.isChecked()
        self.data['channel_1']['name'] = self.returnText(self.wallAdd)
        self.data['channel_1']['id'] = self.returnText(self.wallAdd)

        self.data['channel_2']['selected'] = self.c2.isChecked()
        self.data['channel_2']['name'] = self.returnText(self.wallAdd)
        self.data['channel_2']['id'] = self.returnText(self.wallAdd)

        self.data['channel_3']['selected'] = self.c3.isChecked()
        self.data['channel_3']['name'] = self.returnText(self.wallAdd)
        self.data['channel_3']['id'] = self.returnText(self.wallAdd)

        self.data['channel_4']['selected'] = self.c4.isChecked()
        self.data['channel_4']['name'] = self.returnText(self.wallAdd)
        self.data['channel_4']['id'] = self.returnText(self.wallAdd)

        self.data['channel_5']['selected'] = self.c5.isChecked()
        self.data['channel_5']['name'] = self.returnText(self.wallAdd)
        self.data['channel_5']['id'] = self.returnText(self.wallAdd)

        self.data['channel_6']['selected'] = self.c6.isChecked()
        self.data['channel_6']['name'] = self.returnText(self.wallAdd)
        self.data['channel_6']['id'] = self.returnText(self.wallAdd)

        f = open(os.path.join(os.path.dirname(__file__),"data.json"),'w')
        json.dump(self.data,f)
        f.close()




    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(842, 627)
        self.close = QtWidgets.QPushButton(Dialog)
        self.close.setGeometry(QtCore.QRect(610, 570, 89, 25))
        self.close.setObjectName("close")
        self.start = QtWidgets.QPushButton(Dialog)
        self.start.setGeometry(QtCore.QRect(720, 570, 89, 25))
        self.start.setObjectName("start")
        self.wallAdd = QtWidgets.QPlainTextEdit(Dialog)
        self.wallAdd.setGeometry(QtCore.QRect(180, 110, 211, 31))
        self.wallAdd.setObjectName("wallAdd")
        self.l_wallAdd = QtWidgets.QLabel(Dialog)
        self.l_wallAdd.setGeometry(QtCore.QRect(60, 120, 111, 17))
        self.l_wallAdd.setObjectName("l_wallAdd")
        self.pvtKey = QtWidgets.QPlainTextEdit(Dialog)
        self.pvtKey.setGeometry(QtCore.QRect(180, 150, 211, 31))
        self.pvtKey.setObjectName("pvtKey")
        self.l_pvtKey = QtWidgets.QLabel(Dialog)
        self.l_pvtKey.setGeometry(QtCore.QRect(60, 160, 101, 17))
        self.l_pvtKey.setObjectName("l_pvtKey")
        self.l_wallet_details = QtWidgets.QLabel(Dialog)
        self.l_wallet_details.setGeometry(QtCore.QRect(40, 80, 151, 17))
        self.l_wallet_details.setObjectName("l_wallet_details")
        self.tele_api = QtWidgets.QPlainTextEdit(Dialog)
        self.tele_api.setGeometry(QtCore.QRect(180, 230, 211, 31))
        self.tele_api.setObjectName("tele_api")
        self.l_telegram_details = QtWidgets.QLabel(Dialog)
        self.l_telegram_details.setGeometry(QtCore.QRect(40, 200, 151, 17))
        self.l_telegram_details.setObjectName("l_telegram_details")
        self.l_tele_hash = QtWidgets.QLabel(Dialog)
        self.l_tele_hash.setGeometry(QtCore.QRect(60, 280, 101, 17))
        self.l_tele_hash.setObjectName("l_tele_hash")
        self.l_tele_api = QtWidgets.QLabel(Dialog)
        self.l_tele_api.setGeometry(QtCore.QRect(60, 240, 111, 17))
        self.l_tele_api.setObjectName("l_tele_api")
        self.tele_hash = QtWidgets.QPlainTextEdit(Dialog)
        self.tele_hash.setGeometry(QtCore.QRect(180, 270, 211, 31))
        self.tele_hash.setObjectName("tele_hash")
        self.l_gas = QtWidgets.QLabel(Dialog)
        self.l_gas.setGeometry(QtCore.QRect(60, 420, 101, 17))
        self.l_gas.setObjectName("l_gas")
        self.l_amt = QtWidgets.QLabel(Dialog)
        self.l_amt.setGeometry(QtCore.QRect(60, 380, 111, 17))
        self.l_amt.setObjectName("l_amt")
        self.l_pump_n_pump_settings = QtWidgets.QLabel(Dialog)
        self.l_pump_n_pump_settings.setGeometry(QtCore.QRect(40, 340, 181, 17))
        self.l_pump_n_pump_settings.setObjectName("l_pump_n_pump_settings")
        self.amt = QtWidgets.QPlainTextEdit(Dialog)
        self.amt.setGeometry(QtCore.QRect(180, 370, 211, 31))
        self.amt.setObjectName("amt")
        self.gas = QtWidgets.QPlainTextEdit(Dialog)
        self.gas.setGeometry(QtCore.QRect(180, 410, 211, 31))
        self.gas.setObjectName("gas")
        self.gasPrice = QtWidgets.QPlainTextEdit(Dialog)
        self.gasPrice.setGeometry(QtCore.QRect(180, 450, 211, 31))
        self.gasPrice.setObjectName("gasPrice")
        self.l_gasPrice = QtWidgets.QLabel(Dialog)
        self.l_gasPrice.setGeometry(QtCore.QRect(60, 460, 101, 17))
        self.l_gasPrice.setObjectName("l_gasPrice")
        self.t_id_1 = QtWidgets.QPlainTextEdit(Dialog)
        self.t_id_1.setGeometry(QtCore.QRect(650, 248, 151, 31))
        self.t_id_1.setObjectName("t_id_1")
        self.t_id_2 = QtWidgets.QPlainTextEdit(Dialog)
        self.t_id_2.setGeometry(QtCore.QRect(650, 288, 151, 31))
        self.t_id_2.setObjectName("t_id_2")
        self.t_id_3 = QtWidgets.QPlainTextEdit(Dialog)
        self.t_id_3.setGeometry(QtCore.QRect(650, 328, 151, 31))
        self.t_id_3.setObjectName("t_id_3")
        self.t_id_5 = QtWidgets.QPlainTextEdit(Dialog)
        self.t_id_5.setGeometry(QtCore.QRect(650, 408, 151, 31))
        self.t_id_5.setObjectName("t_id_5")
        self.t_id_6 = QtWidgets.QPlainTextEdit(Dialog)
        self.t_id_6.setGeometry(QtCore.QRect(650, 448, 151, 31))
        self.t_id_6.setObjectName("t_id_6")
        self.t_id_4 = QtWidgets.QPlainTextEdit(Dialog)
        self.t_id_4.setGeometry(QtCore.QRect(650, 368, 151, 31))
        self.t_id_4.setObjectName("t_id_4")
        self.l_tele_channel_title = QtWidgets.QLabel(Dialog)
        self.l_tele_channel_title.setGeometry(QtCore.QRect(440, 170, 141, 17))
        self.l_tele_channel_title.setObjectName("l_tele_channel_title")
        self.t_name_5 = QtWidgets.QPlainTextEdit(Dialog)
        self.t_name_5.setGeometry(QtCore.QRect(490, 408, 151, 31))
        self.t_name_5.setObjectName("t_name_5")
        self.t_name_4 = QtWidgets.QPlainTextEdit(Dialog)
        self.t_name_4.setGeometry(QtCore.QRect(490, 368, 151, 31))
        self.t_name_4.setObjectName("t_name_4")
        self.t_name_2 = QtWidgets.QPlainTextEdit(Dialog)
        self.t_name_2.setGeometry(QtCore.QRect(490, 288, 151, 31))
        self.t_name_2.setObjectName("t_name_2")
        self.t_name_3 = QtWidgets.QPlainTextEdit(Dialog)
        self.t_name_3.setGeometry(QtCore.QRect(490, 328, 151, 31))
        self.t_name_3.setObjectName("t_name_3")
        self.t_name_1 = QtWidgets.QPlainTextEdit(Dialog)
        self.t_name_1.setGeometry(QtCore.QRect(490, 248, 151, 31))
        self.t_name_1.setPlainText("")
        self.t_name_1.setObjectName("t_name_1")
        self.t_name_6 = QtWidgets.QPlainTextEdit(Dialog)
        self.t_name_6.setGeometry(QtCore.QRect(490, 448, 151, 31))
        self.t_name_6.setObjectName("t_name_6")
        self.c1 = QtWidgets.QCheckBox(Dialog)
        self.c1.setGeometry(QtCore.QRect(450, 250, 21, 31))
        self.c1.setText("")
        self.c1.setObjectName("c1")
        self.c2 = QtWidgets.QCheckBox(Dialog)
        self.c2.setGeometry(QtCore.QRect(450, 290, 21, 31))
        self.c2.setText("")
        self.c2.setObjectName("c2")
        self.c3 = QtWidgets.QCheckBox(Dialog)
        self.c3.setGeometry(QtCore.QRect(450, 330, 21, 31))
        self.c3.setText("")
        self.c3.setObjectName("c3")
        self.c4 = QtWidgets.QCheckBox(Dialog)
        self.c4.setGeometry(QtCore.QRect(450, 370, 21, 31))
        self.c4.setText("")
        self.c4.setObjectName("c4")
        self.c5 = QtWidgets.QCheckBox(Dialog)
        self.c5.setGeometry(QtCore.QRect(450, 410, 21, 31))
        self.c5.setText("")
        self.c5.setObjectName("c5")
        self.c6 = QtWidgets.QCheckBox(Dialog)
        self.c6.setGeometry(QtCore.QRect(450, 450, 21, 31))
        self.c6.setText("")
        self.c6.setObjectName("c6")
        self.l_sel = QtWidgets.QLabel(Dialog)
        self.l_sel.setGeometry(QtCore.QRect(440, 210, 41, 17))
        self.l_sel.setObjectName("l_sel")
        self.l_channel_name = QtWidgets.QLabel(Dialog)
        self.l_channel_name.setGeometry(QtCore.QRect(510, 210, 101, 17))
        self.l_channel_name.setObjectName("l_channel_name")
        self.l_channel_id = QtWidgets.QLabel(Dialog)
        self.l_channel_id.setGeometry(QtCore.QRect(680, 210, 81, 17))
        self.l_channel_id.setObjectName("l_channel_id")
        self.pay_txn_hash = QtWidgets.QPlainTextEdit(Dialog)
        self.pay_txn_hash.setGeometry(QtCore.QRect(40, 560, 291, 31))
        self.pay_txn_hash.setObjectName("pay_txn_hash")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 510, 181, 41))
        self.label.setObjectName("label")
        self.instruction_btn = QtWidgets.QPushButton(Dialog)
        self.instruction_btn.setGeometry(QtCore.QRect(720, 530, 89, 25))
        self.instruction_btn.setObjectName("instruction_btn")
        self.reset_btn = QtWidgets.QPushButton(Dialog)
        self.reset_btn.setGeometry(QtCore.QRect(390, 570, 89, 25))
        self.reset_btn.setObjectName("reset_btn")
        self.save_data = QtWidgets.QPushButton(Dialog)
        self.save_data.setGeometry(QtCore.QRect(500, 570, 89, 25))
        self.save_data.setObjectName("save_data")




        self.feedData()
        self.btnFunc()
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.close.setText(_translate("Dialog", "Close"))
        self.start.setText(_translate("Dialog", "Start Bot"))
        self.l_wallAdd.setText(_translate("Dialog", "Wallet Address"))
        self.l_pvtKey.setText(_translate("Dialog", "Private Key"))
        self.l_wallet_details.setText(_translate("Dialog", "Wallet Details"))
        self.l_telegram_details.setText(_translate("Dialog", "Telegram Details"))
        self.l_tele_hash.setText(_translate("Dialog", "Secret Hash"))
        self.l_tele_api.setText(_translate("Dialog", "API Key"))
        self.l_gas.setText(_translate("Dialog", "Gas"))
        self.l_amt.setText(_translate("Dialog", "Amount in BNB"))
        self.l_pump_n_pump_settings.setText(_translate("Dialog", "Pump And Dump Settings"))
        self.l_gasPrice.setText(_translate("Dialog", "Gas Price"))
        self.l_tele_channel_title.setText(_translate("Dialog", "Telegram Channels"))
        self.l_sel.setText(_translate("Dialog", "Select"))
        self.l_channel_name.setText(_translate("Dialog", "Channel Name"))
        self.l_channel_id.setText(_translate("Dialog", "Channel ID"))
        self.label.setText(_translate("Dialog", "Payment Transaction Hash"))
        self.instruction_btn.setText(_translate("Dialog", "Instructions"))
        self.reset_btn.setText(_translate("Dialog", "Reset"))
        self.save_data.setText(_translate("Dialog", "Save Data"))
        

    def btnFunc(self):
        self.close.clicked.connect(self.closefn)
        self.instruction_btn.clicked.connect(self.instWindow)
        self.start.clicked.connect(self.start_bot_fn)
        self.reset_btn.clicked.connect(self.reset)
        self.save_data.clicked.connect(self.save)

    def feedData(self):
        
        self.wallAdd.setPlainText(self.data["wallet_address"])
        self.pvtKey.setPlainText(self.data["private_key"])
        self.tele_api.setPlainText(self.data["telegram_api_key"])
        self.tele_hash.setPlainText(self.data["telegram_hash"])
        self.amt.setPlainText(self.data["amount_BNB"])
        self.gas.setPlainText(self.data["gas"])
        self.gasPrice.setPlainText(self.data["gasPrice"])
        self.t_id_1.setPlainText(self.data["channel_1"]["id"])
        self.t_id_2.setPlainText(self.data["channel_2"]["id"])
        self.t_id_3.setPlainText(self.data["channel_3"]["id"])
        self.t_id_4.setPlainText(self.data["channel_6"]["id"])
        self.t_id_5.setPlainText(self.data["channel_4"]["id"])
        self.t_id_6.setPlainText(self.data["channel_5"]["id"])
        self.t_name_1.setPlainText(self.data["channel_1"]["name"])
        self.t_name_2.setPlainText(self.data["channel_2"]["name"])
        self.t_name_3.setPlainText(self.data["channel_3"]["name"])
        self.t_name_4.setPlainText(self.data["channel_4"]["name"])
        self.t_name_5.setPlainText(self.data["channel_5"]["name"])
        self.t_name_6.setPlainText(self.data["channel_6"]["name"])
        self.pay_txn_hash.setPlainText(self.data['transaction_hash'])
        self.c1.setChecked(self.data["channel_1"]["selected"])
        self.c2.setChecked(self.data["channel_2"]["selected"])
        self.c3.setChecked(self.data["channel_3"]["selected"])
        self.c4.setChecked(self.data["channel_4"]["selected"])
        self.c5.setChecked(self.data["channel_5"]["selected"])
        self.c6.setChecked(self.data["channel_6"]["selected"])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
